<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJM2GNma\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJM2GNma/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJM2GNma.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJM2GNma\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJM2GNma\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'JM2GNma',
    'container.build_id' => 'f394b48e',
    'container.build_time' => 1548260492,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJM2GNma');
